# Custom Layers

Although much of deep learning's sucess can be attributed to the fact that there are a wide range of layers that already exist, sooner or later we will need to build a custom layer...

In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

## Layers Without Parameters

In [3]:
# This layer doesn't have any parameters, it just subtracts the mean from its input.

class CenteredLayer(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

This layer could be incorporated into more complex models

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/Users/patrickrowe/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [7]:
Y = net(torch.rand(4, 8))

# Expect the mean to be close to zero
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

## Layers With Parameters

Requires in_units and units

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.5526,  0.3142, -0.0836],
        [-0.9126, -0.7463, -0.7425],
        [ 0.6579, -1.2442, -0.6582],
        [-0.3294, -0.7204, -0.2565],
        [-2.0992,  0.6322, -0.0892]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])