In [3]:
import torch

## Fundamentals

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Each value in the tensor is called an element, we can check the number of elements, this tensor contains 12 elements.

In [6]:
x.numel()

12

We can check the tensor's shape using x.shape, because this is a one-dimensional tensor (a vector) the shape is a scalar equivalent to its size

In [8]:
x.shape

torch.Size([12])

We can change the shape of the tensor by invoking tensor.resize. Note that the elements are laid out in the tensor one row at a time...

The first element in the reshape matrix is the number of rows, the second is the number of columns.

In [9]:
x.reshape([3, 4])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Because we already know the size of the tensor, we need not specify all elements of the size each time. If we have a tensor with n elements, we know that if we specify want a target shape (h, w) and specify a height h, the width must be n/w. In such cases we can specify -1, and the dimension will be automatically inferred. 


In [19]:
X = x.reshape([3, -1])
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Often we have to work with tensors initialised to all zeros or all ones, this can be done with

In [11]:
torch.zeros((3, 4, 5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [12]:
# or

torch.ones((3, 4, 5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [14]:
# we often want to sample randomly and independently from a probability distribution function, which can be done with

torch.randn((3, 4, 5))

tensor([[[-8.8964e-01, -8.7597e-01,  2.6816e-01,  2.4338e+00, -2.5303e-01],
         [ 1.6838e+00, -2.6752e-01, -1.1219e+00,  8.7520e-01,  6.3621e-01],
         [ 2.7588e-01,  9.9307e-01,  1.4364e+00, -3.4072e+00,  6.2142e-01],
         [ 1.4483e+00,  4.4107e-01,  8.0103e-01,  2.3146e-02, -1.0697e+00]],

        [[ 2.5464e+00,  8.5022e-01,  4.5246e-01,  8.3171e-01,  3.8697e-01],
         [ 6.0358e-01,  1.0341e+00,  2.3750e+00,  1.0787e+00, -6.0307e-01],
         [ 6.9007e-01,  5.6327e-01,  7.0523e-03, -4.9434e-01,  9.1962e-03],
         [-1.2410e+00, -9.8368e-01,  4.6736e-02,  4.7661e-01,  8.9424e-02]],

        [[-5.3632e-01, -5.2646e-01,  6.7998e-01,  1.7140e-01,  1.2365e+00],
         [-1.0682e+00, -5.2055e-01,  3.4670e-01, -3.3354e-01, -8.5613e-01],
         [ 6.0269e-01,  3.6539e-01,  2.3622e+00,  6.7190e-01,  6.8408e-02],
         [-1.0046e+00,  7.2385e-01,  3.8795e-01,  1.4594e-03,  2.2299e-01]]])

In [15]:
# We may also want to specify the elements manually, which can be done by providing a list of lists (nested) presumably this can also be done from a text file or numpy.ndarray

torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Slicing

As with python lists, we can access the elements of a tensor by indexing (beginning at zero) and slicing, with X[start:stop] which will return values from start (included) to stop (NOT included).

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
X[0]

tensor([0., 1., 2., 3.])

In [27]:
X[1:4]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Beyond reading them, we can also write to them

In [34]:
X[1, 2] = 17

#X [row, column]!

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

Values can also be set for many elements at once by using slicing on the left hand side of the assignmment operator


In [38]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])